spring.application.name=news-server
server.port=8481

spring.ai.mcp.server.name=news-server
spring.ai.mcp.server.version=0.0.1

news.api.key=7e1bcf418b2043e683cca145d660f49b
logging.level.org.springframework.ai.mcp=INFO

