spring.application.name=mcp-app-1
spring.ai.openai.api-key=
spring.ai.mcp.client.sse.connections.mcp-server.url=http://localhost:8484
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers.json

